name: run ktlint

on:
  push:
    branches: [kotlin_app] # Just in case main was not up to date while merging PR
  pull_request:
    types: [opened, synchronize]
    
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master
