name: Android CI

on:
  pull_request:
    branches: [ kotlin_app ]
  push:
    branches: [ kotlin_app ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Kotlin Linter (ktlint)
      uses: block42-blockchain-company/ktlint-action@v2.3
    - name: Cache
      uses: actions/cache@v2.1.6
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

      
